//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZQuiz.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TesterQuestion
    {
        public int TesterId { get; set; }
        public int QuestionId { get; set; }
        public Nullable<int> AnsChoiceId { get; set; }
    
        public virtual Choice Choice { get; set; }
        public virtual Question Question { get; set; }
        public virtual Tester Tester { get; set; }
    }
}
